Check database availability instead of trying to create
wallabag/docker pull request #210
Opened 2020-07-31 08:01 UTC by ptman

https://github.com/wallabag/docker/issues/190

2020-07-31 08:53 UTC, j0k3r commented
Shouldn't the setup fail if the ping is false?
Looks like it pass everything (or tests aren't accurate about that).

2020-07-31 09:13 UTC, ptman commented
You're right. Weird module that it doesn't fail if it cannot reach. I also looked at ansible-lint output

2020-08-14 08:11 UTC, ptman commented
The logs are a bit inpenetrable. Any idea what fails?

2020-08-23 20:12 UTC, Spiritus44 requested changes
Hi,
Thanks for your PR.

First i'm not sure to understand why you delete the "posgresql db" and "add postgresql user" tasks. I my mind you should just add the "verify PostgreSQL server is available" task before theses 2 tasks ?

Next you forget to specify the port in your "verify PostgreSQL server is available" task. it's a problem for people like me who use custom port for their pgsql database.

To finish, I tryed to add your task in front of the other pgsql task but I have this error in the log : `[localhost] TASK [verify PostgreSQL server is available] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var fatal: [localhost]: FAILED! => {"msg": "The conditional check 'not pgping.available' failed. The error was: error while evaluating conditional (not pgping.available): 'dict object' has no attribute 'available'"}`
Did I missed something ?

2020-08-23 20:12 UTC, Spiritus44 commented on root/etc/ansible/entrypoint.yml
> +        db: '{{ database_name }}'
I think you forget to specify the port of the pgsql server.
Consider using `port: '{{ database_port }}'`

2020-08-24 04:10 UTC, ptman commented
> First i'm not sure to understand why you delete the "posgresql db" and "add postgresql user" tasks

Creating the database shouldn't be the concern of the wallabag image/container, but instead handled by the postgres container using the provided POSTGRES_DB, POSTGRES_USER and POSTGRES_PASSWORD environment variables ( https://hub.docker.com/_/postgres )

2021-03-24 17:36 UTC, closed without merging