Update shipped php.ini with php-production.ini from PHP 8.1
wallabag/docker pull request #404
Opened 2024-03-10 22:23 UTC by Kdecherf

2024-03-10 22:31 UTC, yguedidi reviewed
were there any customization made before that should be preserved?

2024-03-10 22:38 UTC, Kdecherf commented
@yguedidi I kept customizations :)

2024-03-10 23:01 UTC, yguedidi requested changes

2024-03-11 11:13 UTC, Kdecherf commented on root/etc/php81/php.ini
> +session.gc_probability = 1
It is overridden by Symfony anyway, see https://symfony.com/doc/5.x/session.html#configuring-garbage-collection

> However, some operating systems (e.g. Debian) do their own session handling and set the session.gc_probability variable to 0 to stop PHP doing garbage collection. That's why Symfony now overwrites this value to 1.

2024-03-11 11:20 UTC, yguedidi approved these changes

2024-03-11 11:51 UTC, merged